// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TXP_EF_Core.Models;

public partial class Grade
{
    [Key]
    [Column("GradeID")]
    public int GradeId { get; set; }

    [Required]
    public string GradeName { get; set; }

    [InverseProperty("Grade")]
    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}